import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import TopNavBar from "@/components/shared/top_navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

import toast, { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <TopNavBar />
        <Toaster />
        <main>{children}</main>
      </body>
    </html>
  );
}
