import TopNavBar from "@/components/shared/top_navbar";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

import { Toaster } from "react-hot-toast";
import AppStateProvider from "@/lib/providers/app-state.provider";
import AppSessionProvider from "@/lib/providers/session.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AppStateProvider>
          <AppSessionProvider>
            <TopNavBar />
            <Toaster />
            <main className="relative  md:top-28">{children}</main>
          </AppSessionProvider>
        </AppStateProvider>
      </body>
    </html>
  );
}
